### ISSUE TITLE
Questions about the project

### ISSUE THREAD

**Issue by santteegt** [lacchain/DAVID19-taskforce#33]
Here're some questions about the project:

* Any Official docs/announcements by IDB?
* Is this project going to be deployed on Hyperledger Besu? How many validators will this permissioned blockchain have? Who are they?
* If being deployed on a permission blockchain, who will have access to the data? Everyone? Selected participants?
* Which Countries are currently participating?
* What applications are currently being developed to connect to this solution?
* Who can get involved?
* How do you plan to make it sybil resistant?
* How do you plan to prevent data leakages?

**Comment by AllendeMarcos** [comment]
Thanks for the questions santteegt.

- Any Official docs/announcements by IDB? 

Not yet, as the solution has not been released yet.

- Is this project going to be deployed on Hyperledger Besu? 

Yes.

- How many validators will this permissioned blockchain have? Who are they?

At present, the network has 7 validator nodes run by the IDB and the LACChain partners of the Alliance. All the info here: https://github.com/lacchain/besu-network.

- If being deployed on a permission blockchain, who will have access to the data? Everyone? Selected participants?

Permissioned doesn't mean public. Attending to the International Organization for Standards (ISO) in its publication ISO/TC 307 (https://www.iso.org/committee/6266604.html), blockchain networks can be permissioned or permissionless. Permissioned networks can also be private and public. LACChain Networks are permissioned private. That means that (i) all the information is public, and (ii) everyone can deploy a writer node in the network and broadcast transactions FOR FREE, with no transactional fee or any cost at all. 

See the permissioning process here: https://github.com/lacchain/besu-network/blob/master/PERMISSIONING_PROCESS.md

An ethstats: http://dashboard.lacchain.net/

An a tx explorer: http://explorer.lacchain.net/

- Which Countries are currently participating?

This is a solution for the citizens. Any citizen can download a digital wallet and participate.

- What applications are currently being developed to connect to this solution?

An informative application and a commsite are being developed. Additionally, we will use different digital wallets. In a first, release, we will have REM (by World Data) and KayTrust (by Everis) available.

- Who can get involved?

Anyone. 

- How do you plan to make it sybil resistant?

This is self-attested info, identities are not verified, and information is provided pseudonymously. However, digital wallets will require SMS verification to prevent the creation of multiple users from the same device easily.

- How do you plan to prevent data leakages?

We are incorporating all the existing standards for self-sovereign identity, and there is no personal information at all of the users leaving their digital wallets. Only pseudonimous information about their sex, age, location (with the precision of 1km square), and the COVID info (symptoms, isolation, infection, ...) is publicly stored in a smart contract so everyone can have access to it. Nowhere that pseudonymous info is linked to a real or digital identity.

**Comment by AllendeMarcos** [comment]
Please, close the issue if it answers your questions or ask any other question you may have.
